name: Build Flet APK

on:
  workflow_dispatch:

jobs:
  build-android-apk:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install Flet
        run: |
          pip install -i https://pypi.tuna.tsinghua.edu.cn/simple flet
          
      - name: 设置 Flutter 镜像
        run: |
          export FLUTTER_STORAGE_BASE_URL="https://mirrors.tuna.tsinghua.edu.cn/flutter"
          export PUB_HOSTED_URL="https://mirrors.tuna.tsinghua.edu.cn/dart-pub"
          
      - name: Build APK
        run: |
          flet build apk --name "芮城旅游端" --android-package-name com.ruicheng.travel --icon icon.png
